export const TYPES = {
  SET_TITLE: "SET_TITLE",
  SET_ABOUT: "SET_ABOUT",
  SET_PROFILE: "SET_PROFILE",
  SET_LOGIN: "SET_LOGIN",
  SET_QUIZ:"SET_QUIZ",
  SET_ALLQUIZEZ:"SET_ALLQUIZEZ",
  SET_SINGLEQUESTION:"SET_SINGLEQUESTION",
  SET_SINGLEQUESTION_DELETE:"SET_SINGLEQUESTION_DELETE",
  SET_SINGLEQUESTION_EMPTY:"SET_SINGLEQUESTION_EMPTY",
  UPDATE_ALLQUIZEZ:"UPDATE_ALLQUIZEZ",
  SET_ALLQUIZEZ_NEW_STATE:"SET_ALLQUIZEZ_NEW_STATE"
};
